[general]
import = ["./themes/catppuccin-mocha.toml"]

[window]
decorations = "None"
opacity = 0.8
padding = { x = 4, y = 0 }

[font]
normal = { family = "OperatorMonoLig Nerd Font Mono", style = "Regular" }
italic = { family = "OperatorMonoLig Nerd Font Mono", style = "Italic" }
offset = { x = 0, y = 1 }
size = 16
