# Create a `local.toml` for local settings
# @source https://alacritty.org/config-alacritty.html

[general]
import = ["./themes/catppuccin-mocha.toml", "./local.toml"]

[window]
decorations = "None"
opacity = 0.90
option_as_alt = "OnlyLeft"
padding = { x = 8, y = 0 }

[font]
normal = { family = "OperatorMonoLig Nerd Font Mono", style = "Regular" }
italic = { family = "OperatorMonoLig Nerd Font Mono", style = "Italic" }
offset = { x = 0, y = 1 }
