[custom.git_host]
command = 'getgithost'
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash","--norc","--noprofile"]
style = "bright-yellow bold"
format = "at [$output]($style) "