"use strict";
// PS: New-item -ItemType SymbolicLink -Path $env:APPDATA/Hyper/.hyper.js -Target $env:USERPROFILE/Documents/windows-dotfiles/Hyper/.hyper.js
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 12,
    fontFamily:
      '"FiraMono Nerd Font Mono", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: "rgba(248,28,229,0.8)",
    cursorAccentColor: "#000",
    cursorShape: "BLOCK",
    cursorBlink: true,
    foregroundColor: "#fff",
    backgroundColor: "#000",
    selectionColor: "rgba(248,28,229,0.3)",
    borderColor: "#000",
    css: ".splitpane_divider { background: linear-gradient(to left, #e66465, #9198e5) !important; height: 1px !important; border: unset !important; }",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: true,
    showWindowControls: false,
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#C51E14",
      green: "#1DC121",
      yellow: "#C7C329",
      blue: "#0A2FC4",
      magenta: "#C839C5",
      cyan: "#20C5C6",
      white: "#C7C7C7",
      lightBlack: "#686868",
      lightRed: "#FD6F6B",
      lightGreen: "#67F86F",
      lightYellow: "#FFFA72",
      lightBlue: "#6A76FB",
      lightMagenta: "#FD7CFC",
      lightCyan: "#68FDFE",
      lightWhite: "#FFFFFF",
      limeGreen: "#32CD32",
      lightCoral: "#F08080",
    },
    shell: "pwsh.exe",
    shellArgs: [],
    env: {},
    bell: false,
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,

    // Plugins
    hyperTabs: {},
    paneNavigation: {
      debug: true,
      hotkeys: {
        navigation: {
          up: "alt+k",
          down: "alt+j",
          left: "alt+h",
          right: "alt+l",
        },
        jump_prefix: "ctrl+alt", // completed with 1-9 digits
        permutation_modifier: "shift", // Added to jump and navigation hotkeys for pane permutation
        maximize: "meta+enter",
      },
      showIndicators: false, // Show pane number
      indicatorPrefix: "^⌥", // Will be completed with pane number
      indicatorStyle: {
        // Added to indicator <div>
        display: "none",
        position: "absolute",
        top: 0,
        left: 0,
        fontSize: "10px",
      },
      focusOnMouseHover: false,
      inactivePaneOpacity: 0.6, // Set to 1 to disable inactive panes dimming
    },
  },
  plugins: [
    "hyper-search",
    "hyper-broadcast",
    "hyperterm-summon",
    "hyper-manager",
    "hyper-one-dark",
    "hyper-pane",
    // "hyper-tabs-autohide",
  ],
  localPlugins: [],
  keymaps: {
    "window:devtools": "ctrl+shift+i",
    "window:reload": "ctrl+shift+r",
    "window:reloadFull": "ctrl+shift+f5",
    "window:preferences": "ctrl+,",
    "window:hamburgerMenu": "alt+f",
    "zoom:reset": "ctrl+0",
    "zoom:in": "ctrl+=",
    "zoom:out": "ctrl+-",
    "window:new": "ctrl+shift+n",
    "window:minimize": "ctrl+shift+m",
    "window:zoom": "ctrl+shift+alt+m",
    "window:toggleFullScreen": "f11",
    "window:close": ["ctrl+shift+q", "alt+f4"],
    "tab:new": "ctrl+shift+t",
    "tab:next": ["ctrl+tab"],
    "tab:prev": ["ctrl+shift+tab"],
    "tab:jump:prefix": "ctrl",
    "pane:next": ["ctrl+pageup"],
    "pane:prev": ["ctrl+pagedown"],
    "pane:splitRight": ["ctrl+shift+d", "ctrl+shift+="],
    "pane:splitDown": ["ctrl+shift+e", "ctrl+shift+-"],
    "pane:close": "ctrl+shift+w",
    "editor:undo": "ctrl+shift+z",
    "editor:redo": "ctrl+shift+y",
    "editor:cut": "ctrl+shift+x",
    "editor:copy": "ctrl+shift+c",
    "editor:paste": "ctrl+shift+v",
    "editor:selectAll": "ctrl+shift+a",
    "editor:search": "ctrl+shift+f",
    "editor:search-close": "esc",
    "editor:movePreviousWord": "",
    "editor:moveNextWord": "",
    "editor:moveBeginningLine": "Home",
    "editor:moveEndLine": "End",
    "editor:deletePreviousWord": "ctrl+backspace",
    "editor:deleteNextWord": "ctrl+del",
    "editor:deleteBeginningLine": "ctrl+home",
    "editor:deleteEndLine": "ctrl+end",
    "editor:clearBuffer": "ctrl+shift+k",
    "editor:break": "ctrl+c",
    "plugins:update": "ctrl+shift+u",
  },
};
//# sourceMappingURL=config-default.js.map
